config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'tasks#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :tasks
  get 'signup', to:'users#new'
  resources :users,only:[:index, :show, :new, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :user_id,presence:true
  validates :content,presence:true, length:{maximum:255}
  validates :status,presence:true, length:{maximum:10}
end

app/models/user.rb
class User < ApplicationRecord
  before_save{self.email.downcase!}
  validates :name,presence:true,length:{maximum:50}
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:success]="ログアウトしました"
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
    
      session[:user_id] = @user.id
      return true
    else
      
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action:require_user_logged_in,only:[:index,:show, :edit,:create,:new,:destroy,:update]
  before_action :correct_user, only: [:destroy, :edit, :show, :update]
  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success]="タスクを作成しました"
      redirect_to @task
    else
      flash.now[:danger]="タスク作成に失敗しました"
      render :new
    end
  end
  
  def index
    @tasks = Task.all
  end
  
  def show
    @task = Task.find(params[:id])
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success]="タスクを編集しました"
      redirect_to @task
    else
      flash.now[:danger]="タスクを編集できませんでした"
      render :edit
    end
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:success]="タスクを削除しました"
    redirect_to tasks_url
  end
    
  private
  def task_params
    params.require(:task).permit(:content,:status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action:require_user_logged_in,only:[:index,:show]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tasklist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <%if logged_in?%>
            
            <li><%= link_to  'Profile', user_path(current_user) %></li>
            <li><%= link_to  '新規タスク作成', new_task_path %></li>
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <%else%>
            <li><%= link_to  'Login', login_path %></li>
            <li><%= link_to 'Sign up now!', signup_path %></li>
          <%end%>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    
    <%= csrf_meta_tags %>
    <%if logged_in?%>
      <p>ログイン中のユーザーid:<%=session[:user_id]%></p>
    <%end%>
    

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class = "container">
      <%= render "layouts/flash.messages" %>
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    <%= form_for(@task) do |f| %>
      <% if task.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :status, 'ステータス' %>
        <%= f.text_field :status,class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :content,"タスク" %>
        <%= f.text_field :content,class:'form-control'%>
        <%= f.submit "投稿", class: 'btn btn-primary'%>
      </div>
      
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id=<%= @task.id %>タスクの編集ページ</h1>

<%= render 'form',task:@task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%if @tasks.any? %>
  <table class="table table-borderd">
    <thead>
      <th>id</th>
      <th>タスク</th>
      <th>ステータス</th>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.id,task %></td>
          <td><%= task.content %></td>
          <td><%= task.status %></td>
        </tr>
      <% end %>
      
    </tbody>
  
</table>
<% end %>

app/views/tasks/new.html.erb
<h1>新規作成ページ</h1>


<%= render 'form',task:@task %>

app/views/tasks/show.html.erb
<h1>id=<%= @task.id %>のタスク詳細ページ</h1>
<table class="table table-bordered">
  <thead>
    <th>id</th>
    <th>タスク</th>
    <th>ステータス</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @task.id %></td>
      <td><%= @task.status %></td>
      <td><%= @task.content %></td>
    </tr>
  </tbody>
</table>



<%= link_to "編集する", edit_task_path(@task),class:'btn btn-default' %>
<%= link_to "このタスクを削除する", @task, method: :delete,data:{confirm:"本当に削除してよろしいですか？"},class:'btn btn-danger' %>
 

app/views/users/_users.html.erb
<% if users.any? %>
  <ul>
    <% users.each do |user| %>
      <li>
        <div>
         <%= user.name %>
        </div> 
        <p><%= link_to 'View profile', user_path(user) %></p>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/index.html.erb
<%= render 'users',users:@users%>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.label:name,'Name' %>
        <%= f.text_field:name, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label:email,'Email' %>
        <%= f.email_field:email, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label:password,'Password' %>
        <%= f.password_field:password, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label:password_confirmation,'Confirmation' %>
        <%= f.password_field:password_confirmation, class:"form-control" %>
      </div>
      <%= f.submit 'Signup',class:"btn btn-primary btn-block"%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <p>ユーザー名：<%= @user.name %></p>
</div>

<% if @tasks.any? %>

  <ul>
    <% @tasks.each do |task| %>
      <li>
        <div>
          <p>ステータス：<%= task.status %></p>
        </div>
        <div>
          <p>タスク：<%= link_to task.content,task %></p>
        <div>
      </li>
    <% end %>
  </ul>
<% end %>